### ISSUE TITLE
Migrate build.image -> build.os

### ISSUE THREAD

**Issue by cneskey** [Hive-Systems/pyfair#54]
- [x] migrate to the new config key by October 16 2023
- [x] specify the Python version, you have to use build.tools.python

Example of a valid build section of configuration:
```
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "18"
    rust: "1.64"
    golang: "1.19"
```

# Refs
1. [Use build.os instead of build.image on your configuration file — Read the Docs Blog](https://blog.readthedocs.com/use-build-os-config/)
2. https://docs.readthedocs.io/en/stable/config-file/v2.html#build
